apiVersion: apps/v1
kind: Deployment
metadata:
  name: check-weather
  namespace: check-weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: check-weather
  template:
    metadata:
      labels:
        app: check-weather
    spec:
      serviceAccountName: default
      containers:
        - name: check-weather
          image: 289193905928.dkr.ecr.ap-southeast-2.amazonaws.com/check_weather:976fce45e0c2e35c0738e3f34bd4ec2d4f9d3af7
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: config-volume
              mountPath: /workspace/config
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
      volumes:
        - name: config-volume
          configMap:
            name: check-weather-config
