apiVersion: apps/v1
kind: Deployment
metadata:
  name: check-weather
  namespace: check-weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: check-weather
  template:
    metadata:
      labels:
        app: check-weather
    spec:
      containers:
        - name: check-weather
          image: 289193905928.dkr.ecr.ap-southeast-2.amazonaws.com/check_weather:a4461da9738620199dc8affeacb91f1ce485256b
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: config-volume
              mountPath: /workspace/config
      volumes:
        - name: config-volume
          configMap:
            name: check-weather-config
