apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: check-weather
  name: api-access
rules:
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-access-binding
  namespace: check-weather
subjects:
- kind: ServiceAccount
  name: default
  namespace: check-weather
roleRef:
  kind: Role
  name: api-access
  apiGroup: rbac.authorization.k8s.io 