apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: check-weather
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/louisnguyen88/iac_checkweather.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc #internal K8s service add
    namespace: check-weather
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true